### ISSUE TITLE
Add a Solar Smelter

### ISSUE THREAD

**Issue by Auseawesome** [cech12/SolarCooker#11]
Similar to the Cooker but can smelt anything the normal furnace can do but at 1/4 of the speed of a furnace rather than 1/2.

**Comment by Auseawesome** [comment]
This is different to the config where you can change it to smelting, i think an option that would be slower like a normal furnace is slower than a smoker but can do more. I think a Solar Blaster could also be added as a blast furnace alternative

**Comment by cech12** [comment]
You can configure the Solar Cooker to use the smelting recipes and you can configure the speed factor of the cooker.
Or do you mean to have a second block?

**Comment by Auseawesome** [comment]
Have a new block seperate to the config, a selection of alternatives so you can have all of them with the solar smelter being the easiest to craft and most basic

**Comment by Auseawesome** [comment]
Because the config means you can only have one you can't have multiple different things like a smoker and a blast furnace

Without other things like a solar smelter a campfire can be used instead and is cheaper.

**Comment by cech12** [comment]
I don't see the benefit of this. If you need a solar smelter in your modpack, you can change the config to have one. The "smelting" recipe group contains all recipes (smoking, blasting and normal ones). 

You can also change the smelting recipes via a datapack to let them need more/less time as well as you can change the speed of the solar cooker.
If the crafting recipe of the solar cooker is too simple for your pack, you can change it via datapack, too.

Why do you need more than one solar cooker?

**Comment by Auseawesome** [comment]
Because having a solar smoker and a solar blast furnace covers most things at a quicker speed, having a furnace at the same speed as both means its easier to do stuff, some people want a smoker and a blast furnace not just a furnace

**Comment by Auseawesome** [comment]
The same reason why the blast furnace and smoker were added in the first place, harder to craft more advanced options

**Comment by cech12** [comment]
Like I've said. You can change the recipe config to use the smelting recipes (including the food and ore recipes). You can also change the speed factor to speed up the solar cooker. There are also the reflectors to spped up the solar cooker.

The vanilla blast furnace and the smoker are still included in the game. 

Unfortunately, these reasons do not convince me.

**Comment by Auseawesome** [comment]
But having multiple options at once is impossible having different versions could be necessary for certain modpacks so they could limit you to having only a free food cooker then later a free smelter

**Comment by cech12** [comment]
Are you a creator of a new modpack that should include this?

**Comment by Auseawesome** [comment]
No but i may do in the future and i am making a skyblock pack and would need these features to add it in.
