### ISSUE TITLE
[Bug]: 1.21 Neoforge Failure to Load

### ISSUE THREAD

**Issue by unspunreality** [cech12/SolarCooker#26]
### Minecraft Version

1.21

### Mod Loader

NeoForge

### Mod Loader Version

.91 Beta

### Mod Version

4.0.0.1

### Describe the Issue

Just a failure to load. java.lang.NoSuchMethodError: 'void net.neoforged.neoforge.common.ModConfigSpec.setConfig(com.electronwill.nightconfig.core.CommentedConfig)' shown as error and thats it. No ctd or anything.

### Logs

https://mclo.gs/GFF67aD

**Comment by cech12** [comment]
Thanks for your report! Downgrading Neoforge to 21.0.81 could be a workaround for now until I fix that issue :)

**Comment by cech12** [comment]
Thanks again for your report! The crash is fixed in the upcoming version 1.21-4.1.0.0.
