### ISSUE TITLE
Turning it into a full blown Camping Mod!!!

### ISSUE THREAD

**Issue by SamhitApple** [cech12/SolarCooker#7]
I know it's kinda irrelevant here, but can you add more such stuff to the mod and make it a camping mod? There's currently none for Forge, Fabric has the awesome Campanion mod!

You could add; picnic basket, Picnic mat, tent, chairs, sleeping bags, bear traps, grappling hooks and so much more!

Wouldn't it be cool to look back later and see that it all started with a simple solar cooker!

**Comment by cech12** [comment]
Thanks for your interest and suggestions. :)
But a whole camping mod is out of scope of this mod.
